export const GET_PROGRESS_UPDATES = "GET_PROGRESS_UPDATES";
export const GET_PROGRESS_UPDATES_REQUEST = "GET_PROGRESS_UPDATES_REQUEST";
export const GET_PROGRESS_UPDATES_FAILURE = "GET_PROGRESS_UPDATES_FAILURE";
export const CREATE_PROGRESS_UPDATE = "CREATE_PROGRESS_UPDATE";
export const UPDATE_PROGRESS_UPDATE = "UPDATE_PROGRESS_UPDATE";
export const DELETE_PROGRESS_UPDATE = "DELETE_PROGRESS_UPDATE";
